trigger: 
  - main
pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: function-variables.yml

stages:
- stage: BuildApplication
  displayName: Build
  jobs:
  - template: templates/app-build.yml
    parameters:
      framework: $(framework)
      working_dir: src/ReadIntent

- stage: DeploySlot
  displayName: Slot
  dependsOn: [BuildApplication]
  condition: succeeded()
  jobs:
  - template: templates/app-test-deploy.yml
    parameters:
      environment: $(environment)
      app_name: $(app_name)
      resource_group_name: $(resource_group_name)
      subscription: $(subscription)

- stage: DeployApplication
  displayName: Deploy
  dependsOn: [DeploySlot]
  condition: succeeded()
  jobs:
  - template: templates/app-deploy.yml
    parameters:
      environment: $(environment)
      app_name: $(app_name)
      resource_group_name: $(resource_group_name)
      subscription: $(subscription)
