parameters:
  framework: dotnet
  working_dir: 

jobs:
- job: BuildAndTest
  displayName: Build and Test
  steps:
  - script: |
      cd ${{ parameters.working_dir }}
      dotnet restore
      dotnet build --configuration Release
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--configuration Release --output publish_output'
      projects: '*.csproj'
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false
      workingDirectory: ${{ parameters.working_dir }}
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/${{ parameters.working_dir }}/publish_output"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/${{ parameters.working_dir }}/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(System.DefaultWorkingDirectory)/${{ parameters.working_dir }}/build$(Build.BuildId).zip"
      artifactName: 'drop'