parameters:
  environment: Development
  app_name:
  app_type: functionAppLinux
  resource_group_name:
  subscription:

jobs:
- deployment: GoLiveWithSlot
  displayName: "Make Slot Live"
  environment: ${{ parameters.environment }}
  strategy:
    runOnce: #rolling, canary are the other strategies that are supported
      deploy:
        steps:      
        - task: AzureAppServiceManage@0
          inputs:
            azureSubscription: ${{ parameters.subscriptionName }}
            WebAppName: ${{ parameters.appName }}
            ResourceGroupName: ${{ parameters.resourceGroupName }}
            SourceSlot: staging
            SwapWithProduction: true