parameters:
  environment: Development
  app_name:
  app_type: functionAppLinux
  resource_group_name:
  subscription:

jobs:
- job: DeployFunctionApp
  displayName: "Deploy to Slot"
  steps:
  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      appType: functionAppLinux
      appName: ${{ parameters.app_name }}
      package: $(System.ArtifactsDirectory)/**/*.zip
      deployToSlotOrASE: true
      resourceGroupName: ${{ parameters.resource_group_name }}
      slotName: staging

- deployment: GoLiveWithSlot
  displayName: "Make Slot Live"
  environment: ${{ parameters.environment }}
  strategy:
    runOnce: #rolling, canary are the other strategies that are supported
      deploy:
        steps:      
        - task: AzureAppServiceManage@0
          inputs:
            azureSubscription: ${{ parameters.subscriptionName }}
            WebAppName: ${{ parameters.appName }}
            ResourceGroupName: ${{ parameters.resourceGroupName }}
            SourceSlot: staging
            SwapWithProduction: true